gui:
  authorColors: {}
  nerdFontsVersion: "3"
  tabWidth: 2
  expandFocusedSidePanel: true
  # timeFormat: "02 Jan 06 15:04"

  shortTimeFormat: "15:04"
  showRandomTip: false
  showCommandLog: false
  statusPanelView: allBranchesLog
  # showAuthorColors
git:
  # branchLogCmd: "git log --oneline"
  pagers:
    - pager: delta --dark --paging=never
      colorArg: never
  log:
    order: date-order
    showWholeGraph: true
os:
  editPreset: "nvim"
